# Autoscaling Configuration Template
# This file is generated by Terraform and contains autoscaling configuration

apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-config
  namespace: cluster-autoscaler
data:
  cluster-autoscaler-config: |
    apiVersion: cluster.k8s.io/v1alpha1
    kind: ClusterAutoscaler
    metadata:
      name: cluster-autoscaler
    spec:
      scaleDown:
        enabled: true
        delayAfterAdd: 10m
        delayAfterDelete: 10s
        delayAfterFailure: 3m
        unneededTime: 10m
        utilizationThreshold: 0.5
      scaleUp:
        delayAfterAdd: 10s
        delayAfterDelete: 10s
        delayAfterFailure: 3m
        maxNodeProvisionTime: 15m
      maxNodeProvisionTime: 15m
      okTotalUnreadyCount: 3
      maxTotalUnreadyPercentage: 45
      skipNodesWithLocalStorage: false
      skipNodesWithSystemPods: false
      balanceSimilarNodeGroups: true
      expander: least-waste
      nodeGroups:
%{ for node in worker_nodes ~}
        - name: ${node.name}
          minSize: 0
          maxSize: 1
          machineType: kworker
          labels:
            node.kubernetes.io/instance-type: kworker
            k8s.io/cluster-autoscaler/node-template/label/node.kubernetes.io/instance-type: kworker
          taints:
            - key: node.kubernetes.io/not-ready
              value: "true"
              effect: NoSchedule
%{ endfor ~}

---
# Node group configuration for libvirt
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineSet
metadata:
  name: kworker-machineset
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      cluster.k8s.io/cluster-name: ${cluster_name}
      cluster.k8s.io/machine-type: kworker
  template:
    metadata:
      labels:
        cluster.k8s.io/cluster-name: ${cluster_name}
        cluster.k8s.io/machine-type: kworker
    spec:
      clusterName: ${cluster_name}
      machineType: kworker
      versions:
        kubelet: "1.30.1"
      providerSpec:
        value:
          apiVersion: libvirtproviderconfig/v1alpha1
          kind: LibvirtMachineProviderConfig
          domainMemory: 8192
          domainVcpu: 4
          volume:
            poolName: default
            baseVolumeID: ""
            volumeName: ""
          networkInterfaceName: default
          networkInterfaceAddress: ""
          autostart: false
          uri: qemu:///system
