---
- name: Install base packages on all nodes
  hosts: all
  become: true
  tasks:
    - name: Install essential tools
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - gpg
          - curl
          - ca-certificates
        state: present
        update_cache: yes
        lock_timeout: 1200

- name: Install HA packages on load balancers
  hosts: load_balancer
  become: true
  tasks:
    - name: Install keepalived and haproxy
      ansible.builtin.apt:
        name:
          - keepalived
          - haproxy
        state: present
        update_cache: yes
        lock_timeout: 1200
