---
- name: Configure full load balancer after cluster init
  hosts: load_balancer
  become: true
  tasks:
    - name: Update HAProxy with full backend and health checks
      ansible.builtin.copy:
        dest: "/etc/haproxy/haproxy.cfg"
        content: |
          # Full configuration with health checks
          global
            maxconn 50000
            log /dev/log local0
            user haproxy
            group haproxy
            stats socket /var/lib/haproxy/stats
          
          defaults
            log global
            timeout connect 10s
            timeout client 30s
            timeout server 30s
          
          frontend kubernetes-frontend
            bind *:6443
            mode tcp
            option tcplog
            default_backend kubernetes-backend
          
          backend kubernetes-backend
            option httpchk GET /healthz
            http-check expect status 200
            mode tcp
            option ssl-hello-chk
            balance roundrobin
            server kcontrolplane1 {{ IP_HOST_CP1 }}:6443 check
            server kcontrolplane2 {{ IP_HOST_CP2 }}:6443 check
            server kcontrolplane3 {{ IP_HOST_CP3 }}:6443 check
    
    - name: Restart HAProxy with new configuration
      ansible.builtin.systemd:
        state: restarted
        name: haproxy
