---
- hosts: control1
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

#    - name: Transfer file from control-plane to workers
#      synchronize:
#        src: /etc/kubernetes/admin.conf
#        dest: /home/kubeadmin/.kube/config
##      delegate_to: "{{ ansible_hostname == 'workers' }}"

- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['control1'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
