---
- name: Generate worker join command
  hosts: kcontrolplane1
  become: true
  tasks:
    - name: Get join command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command fact
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout }}"

- name: Join worker nodes to cluster
  hosts: workers
  become: true
  tasks:
    - name: Join cluster
      ansible.builtin.shell: "{{ hostvars['kcontrolplane1'].join_command }} >> /root/node_joined.txt"
      args:
        creates: /root/node_joined.txt
