---
- hosts: control1
  become: yes
  gather_facts: false
  tasks:
    - name: Copy config file to host (1/3)
      shell: cp /etc/kubernetes/admin.conf /etc/kubernetes/config

    - name: Copy config file to host (2/3)
      fetch:
        src: /etc/kubernetes/config
        dest: ~/.kube/
        flat: yes

    - name: Copy config file to host (3/3)
      shell: rm /etc/kubernetes/config
