---
- hosts: control1
  become: yes
  gather_facts: false
  tasks:
    - name: Copy config file to user's kube directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        owner: debian
        mode: 0600
        remote_src: yes
