- hosts: all
  become: yes
  tasks:
    - name: Disable unattended-upgrades and apt-daily services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - unattended-upgrades
        - apt-daily.timer
        - apt-daily-upgrade.timer
      ignore_errors: true  # Ignore if services don't exist

    - name: Wait for apt locks to be released (with timeout)
      wait_for:
        path: "{{ item }}"
        state: absent
        timeout: 600  # 10 minutes max wait
      loop:
        - /var/lib/apt/lists/lock
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
        - /var/cache/apt/archives/lock
      register: lock_wait
      ignore_errors: true  # Allow continuation even if timeout occurs

    - name: Forcefully kill stuck apt processes if wait timed out
      command: |
        fuser -k {{ item }} || true
        rm -f {{ item }}
      loop:
        - /var/lib/apt/lists/lock
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
        - /var/cache/apt/archives/lock
      when: lock_wait.failed  # Only run if wait timed out

    - name: Ensure dpkg is consistent after cleanup
      command: dpkg --configure -a
      ignore_errors: true
