---

- name: Initial setup
  import_playbook: 01-initial.yaml

- name: Install packages
  import_playbook: 02-packages.yaml

- name: Load balancer setup
  import_playbook: 03-lb.yaml

- name: Kubernetes setup
  import_playbook: 04-k8s.yaml

- name: Control plane setup
  import_playbook: 05-control-plane.yaml

- name: Worker setup
  import_playbook: 06-worker.yaml

- name: Kubernetes config
  import_playbook: 07-k8s-config.yaml

# Add this new play to wait for apt locks across all hosts
- hosts: all
  become: yes
  tasks:
    - name: Wait for automatic apt updates to complete
      wait_for:
        path: /var/lib/apt/lists/lock
        state: absent
      retries: 30  # Retry up to 30 times (5 minutes total)
      delay: 10    # Wait 10 seconds between retries
