---
- hosts: control_plane
  become: yes
  tasks:
    - name: Reset Kubernetes cluster
      shell: |
        kubeadm reset --force
        rm -rf ~/.kube/
        rm -rf /etc/kubernetes/
        rm -rf /var/lib/kubelet/
        rm -rf /var/lib/etcd/
        iptables -F
        iptables -t nat -F
        iptables -t mangle -F
        iptables -X
      ignore_errors: true  # Allow continuation even if some commands fail
